### ISSUE TITLE
Crash when removing Corssing Gate

### ISSUE THREAD

**Issue by CaptainPowerTurtle** [CSX8600/trafficcontrol#1]
Hello, when i remove the crossing gate, the game just crash, i think it has something to do with optifine?

`[23:36:09] [main/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209) ~[awu$a.class:?]
	at com.clussmanproductions.trafficcontrol.tileentity.CrossingGateGateTileEntity.getRenderBoundingBox(CrossingGateGateTileEntity.java:294) ~[CrossingGateGateTileEntity.class:?]
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
	at net.optifine.reflect.Reflector.call(Reflector.java:961) ~[Reflector.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:998) ~[buy.class:?]
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:375) ~[ShadersRender.class:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4097) ~[Shaders.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1592) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

**Comment by CSX8600** [comment]
Nope, Optifine did not cause this.  I've fixed this issue - you can download the latest file to solve this problem.
