### ISSUE TITLE
crash after mod update

### ISSUE THREAD

**Issue by otakup0pe** [CSX8600/trafficcontrol#15]
```
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=powered, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=trafficcontrol:concrete_barrier, properties=[dye, facing]}
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
        at com.clussmanproductions.trafficcontrol.tileentity.StreetLightDoubleTileEntity.onLoad(StreetLightDoubleTileEntity.java:49)
        at net.minecraft.world.World.func_175700_a(World.java:1924)
        at net.minecraft.world.World.func_147448_a(World.java:1951)
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```
works fine on a fresh world, but existing world will crash :(

old version `0.2.0`, new version `0.2.2`

**Comment by otakup0pe** [comment]
huh. even after reverting to `0.2.0` and a pre-update backup it's still crashing with this, so that's fun.

for more context, this is on a server. don't have any old worlds kicking around on single player to test with.

**Comment by otakup0pe** [comment]
after chatting in discord gonna consider this a machine elf not worth fighting
