### ISSUE TITLE
Issue with traffic lights/bulbs on server

### ISSUE THREAD

**Issue by ttaeko** [CSX8600/trafficcontrol#9]
Whenever I put bulbs in via clicking to attach the item to the pointer and clicking again to drop in the traffic light, it tends to stay in place in the inventory. I also saw some duplication of items that were not interacted with in the menu, such as the chestplate/elytra slot. By using the shift-click method I am able to get the bulbs in the traffic light, but I believe this error is thrown when trying to use the lights with bulbs inside with the controller:

[08:11:28] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174822_a(DF)Lnet/minecraft/util/math/RayTraceResult;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174822_a(DF)Lnet/minecraft/util/math/RayTraceResult;
	at com.clussmanproductions.trafficcontrol.item.ItemTrafficLightFrame.func_77659_a(ItemTrafficLightFrame.java:48) ~[ItemTrafficLightFrame.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

any ideas what this could be? maybe certain libraries weren't added to the build path?
thanks! I love this mod and it really helps improve my server!

**Comment by CSX8600** [comment]
Hopefully fixing all these issues when #7 gets put in
